// Generated by /design-sync — barrel entry scoping the design-system export
// surface for claude.ai/design. Named-exports every scoped component (default
// exports re-exported as named) so each lands on window.StockUI.*.

// Side-effect: initialize i18next (English resources, synchronous) so
// useTranslation() components render real copy instead of raw keys in previews.
import "./src/i18n";

export { Badge } from "@/components/ui/badge";
export { Button } from "@/components/ui/button";
export { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card";
export {
  Command, CommandDialog, CommandEmpty, CommandGroup, CommandInput,
  CommandItem, CommandList, CommandSeparator, CommandShortcut,
} from "@/components/ui/command";
export {
  Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle,
  DialogDescription, DialogFooter, DialogClose,
} from "@/components/ui/dialog";
export {
  DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem,
  DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuGroup,
  DropdownMenuCheckboxItem, DropdownMenuRadioGroup, DropdownMenuRadioItem,
  DropdownMenuSub, DropdownMenuSubTrigger, DropdownMenuSubContent, DropdownMenuShortcut,
} from "@/components/ui/dropdown-menu";
export { Input } from "@/components/ui/input";
export { Label } from "@/components/ui/label";
export { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";
export { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
export { Separator } from "@/components/ui/separator";
export { Skeleton } from "@/components/ui/skeleton";
export { Switch } from "@/components/ui/switch";
export { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
export { Toaster } from "@/components/ui/sonner";
export { Toggle } from "@/components/ui/toggle";
export { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
export { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from "@/components/ui/tooltip";

export { default as CacheBadge } from "@/components/common/CacheBadge";
export { default as ChartCard } from "@/components/common/ChartCard";
export { default as StatCard } from "@/components/common/StatCard";
export { default as SymbolSearch } from "@/components/common/SymbolSearch";
export { ToggleBar, MultiToggleBar } from "@/components/common/ToggleBar";
export { default as WatchlistButton } from "@/components/common/WatchlistButton";
export { default as SignalCard } from "@/components/SignalCard";
